version: '3.8'

services:
  dscope_shiviz:
    build:
      context: .
      dockerfile: docker/shiviz/Dockerfile
    ports:
      - "${SHIVIZ_PORT}:80"
    container_name: dscope_shiviz_nginx
    restart: unless-stopped
    volumes:
      - ./log:/usr/share/nginx/html/log